version: '3'
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: flats
      POSTGRES_USER: kraljak
      POSTGRES_PASSWORD: 123456

  web:
    build: .
    container_name: web
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  scrapy:
    build: .  # You can specify the path to your Scrapy project's Dockerfile
    container_name: scrapy
    volumes:
      - .:/app  # Assuming your Scrapy project is in the current directory
    depends_on:
      - db
