version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: flats
      POSTGRES_USER: kraljak
      POSTGRES_PASSWORD: 123456
  web:
    build: .
    command: python run.py
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
