version: '3'
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: flats
      POSTGRES_USER: kraljak
      POSTGRES_PASSWORD: 123456

  web:
    build: .
    container_name: web
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
